### ISSUE TITLE
move the package to an org?

### ISSUE THREAD

**Issue by CarloLucibello** [SciML/ComponentArrays.jl#275]
Simple PRs,like #272 and #273 , which update the package compat bounds,
are taking a long time to be merged. This is blocking users' environments and downstream development
https://github.com/LuxDL/Lux.jl/issues/1061

Maybe it is better to move the package to an org like JuliaArrays in order to help maintenance.

Also relaxing the policy in
Settings -> Actions -> General -> Approval for running fork pull request workflows from contributors
allow to automatically trigger the workflows in those PRs.

**Comment by jonniediegelman** [comment]
I'm fine moving it to an org. I unfortunately have a pretty limited amount of time to get to issues these days. I know @ChrisRackauckas has also talked about bringing it into SciML before as well. Whichever works best is fine for me.

**Comment by avik-pal** [comment]
I have sufficient permissions (on SciML org end) to move this to SciML

**Comment by jonniediegelman** [comment]
Okay cool. Let's do that then. I imagine its a somewhat complicated process, so I can look into what I need to do to transfer it this weekend.

**Comment by avik-pal** [comment]
Sounds good.

I think we need to add you as a member of SciML then you will have permission to transfer.

**Comment by jonniediegelman** [comment]
Okay. It should probably be [my non-work account](https://github.com/jonniedie) since that's the one that owns this repo.

**Comment by ChrisRackauckas** [comment]
I gave an invite.
